
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 22 16:03:19 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int DIVEQUALS = 31;
  public static final int INCREMENT = 15;
  public static final int CHAR = 38;
  public static final int CONST = 8;
  public static final int EQUALS = 7;
  public static final int L_PAREN = 11;
  public static final int SEMI = 5;
  public static final int TAR = 27;
  public static final int R_PAREN = 12;
  public static final int REALAT = 26;
  public static final int MINUS = 19;
  public static final int DECREMENT = 16;
  public static final int MODEQUALS = 32;
  public static final int ADDEQUALS = 28;
  public static final int SUBEQUALS = 29;
  public static final int BOOL = 37;
  public static final int COMMA = 6;
  public static final int L_INDEXER = 9;
  public static final int PLUS = 20;
  public static final int MULTIPLY = 21;
  public static final int DOT = 17;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int NUMBER = 36;
  public static final int MODULATE = 23;
  public static final int IDENT = 34;
  public static final int VOID = 35;
  public static final int L_BRACE = 3;
  public static final int R_BRACE = 4;
  public static final int READ = 13;
  public static final int MULEQUALS = 30;
  public static final int PROG = 2;
  public static final int DOLAREQUALS = 33;
  public static final int AT = 25;
  public static final int R_INDEXER = 10;
  public static final int PRINT = 14;
}

